#!/usr/bin/env python3
"""tools/asm-corpus.py - what the Forth assembler has to match (SELF-HOSTING.md M0)

Assembles relfasm64.S with GNU as, disassembles its code - from _start
to dispatch256, where the tables begin - and reduces it to instruction
SHAPES: the mnemonic and operands with registers and size keywords kept
and numbers generalised to N, plus the encoding's length for jumps and
calls (the short and near forms are the choice an assembler makes). For
each shape it keeps one real instance and its bytes, as GNU as chose
them. Written to tests/asm-corpus.txt, one shape a line:

    <bytes in hex>  <instruction as objdump prints it>

That file is M0's test: the Forth assembler must produce those bytes
for every line. (Iteration 537.)
"""
import os, re, subprocess, sys, tempfile, collections
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
subprocess.run(['make', '-s', 'relfasm-ops.S', 'relfasm-consts.S'], check=True)
obj = os.path.join(tempfile.mkdtemp(prefix='relf-corpus-'), 'r.o')
subprocess.run(['cc', '-c', '-o', obj, 'relfasm64.S'], check=True)
syms = {}
for line in subprocess.run(['nm', '-n', obj], capture_output=True, text=True, check=True).stdout.split('\n'):
    f = line.split()
    if len(f) == 3: syms[f[2]] = int(f[0], 16)
start, stop = syms['_start'], syms['dispatch256']
# The LINKED file, as the Makefile links it: in the object file every
# symbol's address is still a 0 waiting for the linker, and the bytes are
# not the ones M3 compares against (the first version read the object).
BASE = 0x400000
flat = obj + '.bin'
subprocess.run(['ld', '-Ttext=0x%x' % BASE, '--oformat', 'binary', '-o', flat, obj], check=True)
# --insn-width=16: every instruction's bytes on its own line - by default
# objdump wraps after 7 and continues on a line with no text, which the
# parser skipped, cutting every longer instruction short (Iteration 537)
dis = subprocess.run(['objdump', '-D', '-b', 'binary', '-m', 'i386:x86-64', '-M', 'intel', '--insn-width=16',
                      '--adjust-vma=0x%x' % BASE, '--start-address=0x%x' % (BASE + start),
                      '--stop-address=0x%x' % (BASE + stop), flat],
                     capture_output=True, text=True, check=True).stdout
insns = []
for line in dis.split('\n'):
    m = re.match(r'\s*([0-9a-f]+):\t([0-9a-f ]+?)\s*\t(.*)$', line)
    if not m: continue
    text = re.sub(r'\s+', ' ', m.group(3).split('#')[0]).strip()
    text = re.sub(r' <[^>]*>', '', text)                 # objdump's target names
    insns.append((m.group(2).replace(' ', ''), text))

def shape(bytes_, text):
    mn = text.split(' ', 1)[0]
    ops = text[len(mn):]
    if mn.startswith('j') or mn == 'call':
        if re.match(r'^\s*[0-9a-f]+$', ops):              # a relative target
            return '%s rel%d' % (mn, 8 if len(bytes_) // 2 == 2 else 32)
    ops = re.sub(r'0x[0-9a-f]+|\b\d+\b', 'N', ops)
    return mn + ops

seen = collections.OrderedDict()
for b, t in insns:
    seen.setdefault(shape(b, t), (b, t))
with open('tests/asm-corpus.txt', 'w') as out:
    out.write('# tests/asm-corpus.txt - generated by tools/asm-corpus.py from relfasm64.S\n')
    out.write('# one line per instruction shape: GNU as bytes, then the instruction\n')
    for s, (b, t) in seen.items():
        out.write('%-30s %s\n' % (b, t))
mn = collections.Counter(t.split(' ', 1)[0] for b, t in insns)
print('%d instructions in %d bytes of code; %d distinct shapes; %d mnemonics'
      % (len(insns), stop - start, len(seen), len(mn)))
