/* tools/proto-bytecode.c - THROWAWAY PROTOTYPE, Iteration 141.
 *
 * Executes ONE real word from shell.4 - VALID-NAME? ( c-addr u --- f )
 * - and its colon-word closure, in two encodings, and checks that they
 * agree on every input before timing them:
 *
 *   CELL   one host cell per token, LIT/BRANCH/?BRANCH/(LOOP) followed
 *          by an operand cell, calls as relative offsets. This is what
 *          RelF compiles today.
 *   BYTE   one byte for primitives and literals under 64, two for
 *          calls, three for branches. Token-threaded: a call is an
 *          INDEX into a word table, not an offset.
 *
 * Both programs are generated by tools/proto-gen.py from the actual
 * token stream of the actual image - not hand-written, not synthetic.
 * Run it to regenerate proto_gen.h.
 *
 * Calls are given two bytes even though this program has four words and
 * one byte would do, because the real image has 817 call targets.
 * Flattering the encoding here would make the whole exercise pointless.
 *
 * What this does NOT do, and what a real port still has to face:
 *   - No cross.4. Nothing here compiles Forth source to bytes.
 *   - No save-system.4, no position independence, no relocation.
 *   - (DO)/(LOOP)/I/UNLOOP are C primitives here. (LOOP) reads an
 *     inline operand through the return stack, exactly as (S") does,
 *     so it is encoding-specific by nature - a real port must rewrite
 *     every word of that shape. This prototype found that class of
 *     problem by failing to generate until it was handled.
 *   - A byte stream has no cell alignment, so HERE, ALIGN and , inside
 *     a definition body all change meaning. That is the actual work.
 */

#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <time.h>

typedef intptr_t CELL_T;
#include "proto_gen.h"

static CELL_T ds[64], rs[64];
static int dsp, rsp;
#define PUSH(x) (ds[dsp++] = (CELL_T)(x))
#define POP()   (ds[--dsp])
#define RPUSH(x)(rs[rsp++] = (CELL_T)(x))
#define RPOP()  (rs[--rsp])

static double now(void) {
    struct timespec ts; clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec + ts.tv_nsec / 1e9;
}

/* ------------------------------------------------------------------ */
static CELL_T run_cell(const char *s, CELL_T len) {
    static void *tab[NPRIMS];
    CELL_T t, a, b, c; long ip;
    tab[0]=&&p_do;   tab[1]=&&p_loop; tab[2]=&&p_add;  tab[3]=&&p_lt;
    tab[4]=&&p_eq;   tab[5]=&&p_tor;  tab[6]=&&p_qbr;  tab[7]=&&p_and;
    tab[8]=&&p_cfe;  tab[9]=&&p_drop; tab[10]=&&p_dup; tab[11]=&&p_exit;
    tab[12]=&&p_i;   tab[13]=&&p_lit; tab[14]=&&p_over;tab[15]=&&p_rfrom;
    tab[16]=&&p_rat; tab[17]=&&p_rot; tab[18]=&&p_swap;tab[19]=&&p_unloop;

    dsp = rsp = 0;
    PUSH((CELL_T)(intptr_t)s); PUSH(len);
    RPUSH(-1);                      /* sentinel: EXIT here means done */
    ip = ROOT_CELL;

#define NEXT() do { t = cellprog[ip++]; \
        if (t & 1) goto *tab[(t >> 2) & 0x3ff]; \
        RPUSH(ip); ip += t; goto *(void *)0; } while (0)
    /* calls handled inline below instead of the unreachable goto */
    for (;;) {
        t = cellprog[ip++];
        if (!(t & 1)) { RPUSH(ip); ip += t >> 2; continue; }
        goto *tab[(t >> 2) & 0x3ff];
    p_do:    a = POP(); b = POP(); RPUSH(b); RPUSH(a);           continue;
    p_loop:  a = RPOP(); b = RPOP(); a++;
             if (a == b) { ip++; }
             else { RPUSH(b); RPUSH(a); ip += cellprog[ip]; }    continue;
    p_add:   a = POP(); ds[dsp-1] += a;                          continue;
    p_lt:    a = POP(); ds[dsp-1] = (ds[dsp-1] <  a) ? -1 : 0;   continue;
    p_eq:    a = POP(); ds[dsp-1] = (ds[dsp-1] == a) ? -1 : 0;   continue;
    p_tor:   RPUSH(POP());                                       continue;
    p_qbr:   if (POP()) ip++; else ip += cellprog[ip];            continue;
    p_and:   a = POP(); ds[dsp-1] &= a;                          continue;
    p_cfe:   ds[dsp-1] = *(unsigned char *)(intptr_t)ds[dsp-1];  continue;
    p_drop:  dsp--;                                              continue;
    p_dup:   ds[dsp] = ds[dsp-1]; dsp++;                         continue;
    p_exit:  a = RPOP(); if (a < 0) return POP(); ip = a;        continue;
    p_i:     PUSH(rs[rsp-1]);                                    continue;
    p_lit:   PUSH(cellprog[ip++]);                               continue;
    p_over:  ds[dsp] = ds[dsp-2]; dsp++;                         continue;
    p_rfrom: PUSH(RPOP());                                       continue;
    p_rat:   PUSH(rs[rsp-1]);                                    continue;
    p_rot:   a = ds[dsp-3]; ds[dsp-3] = ds[dsp-2];
             ds[dsp-2] = ds[dsp-1]; ds[dsp-1] = a;               continue;
    p_swap:  a = ds[dsp-1]; ds[dsp-1] = ds[dsp-2]; ds[dsp-2] = a;continue;
    p_unloop:rsp -= 2;                                           continue;
    }
#undef NEXT
    (void)c;
}

/* ------------------------------------------------------------------ */
static CELL_T run_byte(const char *s, CELL_T len) {
    static void *tab[256];
    CELL_T a, b; long ip; unsigned x; int i;
    for (i = 0; i < 256; i++) tab[i] = &&b_bad;
    tab[0]=&&q_do;   tab[1]=&&q_loop; tab[2]=&&q_add;  tab[3]=&&q_lt;
    tab[4]=&&q_eq;   tab[5]=&&q_tor;  tab[6]=&&q_qbr2; tab[7]=&&q_and;
    tab[8]=&&q_cfe;  tab[9]=&&q_drop; tab[10]=&&q_dup; tab[11]=&&q_exit;
    tab[12]=&&q_i;   tab[13]=&&q_lit; tab[14]=&&q_over;tab[15]=&&q_rfrom;
    tab[16]=&&q_rat; tab[17]=&&q_rot; tab[18]=&&q_swap;tab[19]=&&q_unloop;
    for (i = 0x30; i < 0x70; i++) tab[i] = &&q_smalllit;
    tab[B_LITN] = &&q_litn; tab[B_BR] = &&q_br; tab[B_QBR] = &&q_qbr2;
    for (i = B_CALL; i < 256; i++) tab[i] = &&q_call;

    dsp = rsp = 0;
    PUSH((CELL_T)(intptr_t)s); PUSH(len);
    RPUSH(-1);
    ip = ROOT_BYTE;

    for (;;) {
        x = byteprog[ip++];
        goto *tab[x];
    q_do:    a = POP(); b = POP(); RPUSH(b); RPUSH(a);           continue;
    q_loop:  a = RPOP(); b = RPOP(); a++;
             if (a == b) { ip += 2; }
             else { RPUSH(b); RPUSH(a);
                    { int16_t d = (int16_t)(byteprog[ip] | (byteprog[ip+1] << 8));
                      ip += 2 + d; } }                           continue;
    q_add:   a = POP(); ds[dsp-1] += a;                          continue;
    q_lt:    a = POP(); ds[dsp-1] = (ds[dsp-1] <  a) ? -1 : 0;   continue;
    q_eq:    a = POP(); ds[dsp-1] = (ds[dsp-1] == a) ? -1 : 0;   continue;
    q_tor:   RPUSH(POP());                                       continue;
    q_and:   a = POP(); ds[dsp-1] &= a;                          continue;
    q_cfe:   ds[dsp-1] = *(unsigned char *)(intptr_t)ds[dsp-1];  continue;
    q_drop:  dsp--;                                              continue;
    q_dup:   ds[dsp] = ds[dsp-1]; dsp++;                         continue;
    q_exit:  a = RPOP(); if (a < 0) return POP(); ip = a;        continue;
    q_i:     PUSH(rs[rsp-1]);                                    continue;
    q_over:  ds[dsp] = ds[dsp-2]; dsp++;                         continue;
    q_rfrom: PUSH(RPOP());                                       continue;
    q_rat:   PUSH(rs[rsp-1]);                                    continue;
    q_rot:   a = ds[dsp-3]; ds[dsp-3] = ds[dsp-2];
             ds[dsp-2] = ds[dsp-1]; ds[dsp-1] = a;               continue;
    q_swap:  a = ds[dsp-1]; ds[dsp-1] = ds[dsp-2]; ds[dsp-2] = a;continue;
    q_unloop:rsp -= 2;                                           continue;
    q_smalllit: PUSH((CELL_T)(x - 0x30));                        continue;
    q_lit:   /* the byte form uses q_litn or q_smalllit */
    q_litn:  { int32_t v = (int32_t)((uint32_t)byteprog[ip]
                        | ((uint32_t)byteprog[ip+1] << 8)
                        | ((uint32_t)byteprog[ip+2] << 16)
                        | ((uint32_t)byteprog[ip+3] << 24));
               ip += 4; PUSH((CELL_T)v); }                       continue;
    q_br:    { int16_t d = (int16_t)(byteprog[ip] | (byteprog[ip+1] << 8));
               ip += 2 + d; }                                    continue;
    q_qbr2:  { int16_t d = (int16_t)(byteprog[ip] | (byteprog[ip+1] << 8));
               if (POP()) ip += 2; else ip += 2 + d; }           continue;
    q_call:  { unsigned w = ((x - B_CALL) << 8) | byteprog[ip++];
               RPUSH(ip); ip = wordbyte[w]; }                    continue;
    b_bad:   fprintf(stderr, "byte %u at %ld has no handler\n", x, ip - 1);
             return -999;
    }
}

/* ------------------------------------------------------------------ */
int main(void) {
    static const char *cases[] = {
        "", "x", "_", "9", "9x", "x9", "PATH", "_foo_BAR9", "a-b",
        "HOME", "1PATH", "__", "z", "A1", "has space", "e\xffz"
    };
    int n = (int)(sizeof cases / sizeof *cases), i, bad = 0;

    printf("VALID-NAME? from shell.4, %d words, %d primitives\n",
           NWORDS, NPRIMS);
    printf("cell program %d cells = %d bytes   byte program %d bytes"
           "   ratio %.2fx\n\n",
           CELLN, (int)(CELLN * sizeof(CELL_T)), BYTEN,
           (double)(CELLN * sizeof(CELL_T)) / BYTEN);

    for (i = 0; i < n; i++) {
        CELL_T len = (CELL_T)strlen(cases[i]);
        CELL_T c = run_cell(cases[i], len);
        CELL_T b = run_byte(cases[i], len);
        printf("  %-12s cell=%-3ld byte=%-3ld %s\n", cases[i],
               (long)c, (long)b, c == b ? "ok" : "*** DISAGREE ***");
        if (c != b) bad = 1;
    }
    if (bad) { printf("\nencodings disagree; timing withheld\n"); return 1; }

    double bc = 1e9, bb = 1e9;
    for (int rep = 0; rep < 5; rep++) {
        double t0 = now();
        for (long k = 0; k < 300000; k++)
            for (i = 0; i < n; i++) run_cell(cases[i], (CELL_T)strlen(cases[i]));
        double t1 = now(); if (t1 - t0 < bc) bc = t1 - t0;

        t0 = now();
        for (long k = 0; k < 300000; k++)
            for (i = 0; i < n; i++) run_byte(cases[i], (CELL_T)strlen(cases[i]));
        t1 = now(); if (t1 - t0 < bb) bb = t1 - t0;
    }
    printf("\ncell %.0f ms   byte %.0f ms   byte/cell %.3f\n",
           bc * 1000, bb * 1000, bb / bc);
    return 0;
}
